export const dealers = [
  {
    name: "Ravi Kumar",
    phone: "+91 9876543210",
    email: "ravi@example.com",
    office_address: "Shop 12, Market Complex, Noida Sector 62",
    shop_name: "Ravi Realty",
    location: "Noida",
    sub_location: "Sector 62",
  },
  {
    name: "Pooja Sharma",
    phone: "+91 9876501234",
    email: "pooja@example.com",
    office_address: "Shop 3, Alpha Plaza, Alpha 1",
    shop_name: "Pooja Homes",
    location: "Greater Noida",
    sub_location: "Alpha 1",
  },
  {
    name: "Amit Verma",
    phone: "+91 9811122233",
    email: "amit@example.com",
    office_address: "Shop 21, GIP Mall",
    shop_name: "North Estate",
    location: "Noida",
    sub_location: "Sector 18",
  },
  {
    name: "Neha Gupta",
    phone: "+91 9822233344",
    email: "neha@example.com",
    office_address: "Office 5, DLF Cybercity",
    shop_name: "Metro Realtors",
    location: "Gurgaon",
    sub_location: "DLF Phase 2",
  },
  {
    name: "Suresh Yadav",
    phone: "+91 9833344455",
    email: "suresh@example.com",
    office_address: "Shop 8, Sector 15 Market",
    shop_name: "Skyline Properties",
    location: "Noida",
    sub_location: "Sector 15",
  },
  {
    name: "Priya Singh",
    phone: "+91 9844455566",
    email: "priya@example.com",
    office_address: "Shop 11, Gaur City",
    shop_name: "City Homes",
    location: "Greater Noida",
    sub_location: "Gaur City",
  },
  {
    name: "Rahul Mehta",
    phone: "+91 9855566677",
    email: "rahul@example.com",
    office_address: "Connaught Place Block A",
    shop_name: "Central Realty",
    location: "Delhi",
    sub_location: "CP",
  },
  {
    name: "Anita Desai",
    phone: "+91 9866677788",
    email: "anita@example.com",
    office_address: "Shop 2, Alpha 2 Market",
    shop_name: "Desai Estates",
    location: "Greater Noida",
    sub_location: "Alpha 2",
  },
  {
    name: "Mohit Arora",
    phone: "+91 9877788899",
    email: "mohit@example.com",
    office_address: "Saket District Centre",
    shop_name: "South Realty",
    location: "Delhi",
    sub_location: "Saket",
  },
  {
    name: "Kavita Rao",
    phone: "+91 9888899900",
    email: "kavita@example.com",
    office_address: "Huda City Centre",
    shop_name: "Prime Properties",
    location: "Gurgaon",
    sub_location: "Sector 29",
  },
];
