const Locations = [
  "Connaught Place",
  "Karol Bagh",
  "Chandni Chowk",
  "Lajpat Nagar",
  "Rajouri Garden",
  "Saket",
  "Vasant Kunj",
  "Dwarka",
  "Janakpuri",
  "Punjabi Bagh",
  "Pitampura",
  "Rohini",
  "Shahdara",
  "Laxmi Nagar",
  "Preet Vihar",
  "Mayur Vihar",
  "Okhla",
  "Greater Kailash",
  "Hauz Khas",
  "South Extension",
  "Green Park",
  "Malviya Nagar",
  "Nehru Place",
  "Defence Colony",
  "Jangpura",
  "Model Town",
  "Civil Lines",
  "Ashok Vihar",
  "Kalkaji",
  "Tilak Nagar"
];

export default Locations;
