// src/constants/locations.js
export const locations = [
  {
    location: "Noida",
    subLocation: [
      "Electronic City",
      "Sector 62",
      "Sector 59",
      "Sector 61",
      "Sector 52",
      "Sector 34",
      "City Centre",
      "Golf Course",
      "Botanical Garden",
      "Sector 18",
      "Sector 16",
      "Sector 15",
      "Sector 51",
      "Sector 50 (Rainbow)",
      "Sector 76",
      "Sector 101",
      "Sector 81",
      "NSEZ",
      "Sector 83",
      "Sector 137",
      "Sector 142",
      "Sector 143",
      "Sector 144",
      "Sector 145",
      "Sector 146",
      "Sector 147",
      "Sector 148",
    ],
  },
  {
    location: "Mayur Vihar",
    subLocation: [
      "Extension",
      "I",
      "Pocket-I",
      "Mandawali – West Vinod Nagar",
      "East Vinod Nagar – Mayur Vihar-II",
    ],
  },
  {
    location: "Other Delhi",
    subLocation: [
      "New Ashok Nagar",
      "Akshardham",
      "Yamuna Bank",
      "Indraprastha",
      "Laxmi Nagar",
      "Preet Vihar",
      "Nirman Vihar",
      "Karkarduma",
      "Karkarduma Court",
      "Anand Vihar",
      "Krishna Nagar",
      "Trilokpuri – Sanjay Lake",
      "IP Extension",
    ],
  },
  {
    location: "Vaishali Line",
    subLocation: ["Kaushambi", "Vaishali"],
  },
  {
    location: "Greater Noida",
    subLocation: [
      "Knowledge Park II",
      "Pari Chowk",
      "Alpha 1",
      "Delta 1",
      "GNIDA Office",
      "Depot Station",
    ],
  },
];
